name: Trigger auto deployment for feature-toggles-hello-world

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main, kubecon-sample ]
      
  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
            login-server: helloworldfeaturetoggles.azurecr.io
            username:  ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
            password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}  
      - run: |
          docker build ${{ github.workspace }}/HelloWorld -t helloworldfeaturetoggles.azurecr.io/helloworld:${{ github.sha }}
          docker push helloworldfeaturetoggles.azurecr.io/helloworld:${{ github.sha }}

      - name: Login to Octopus Deploy 🐙
        uses: OctopusDeploy/login@v1
        with: 
          server: https://samples.octopus.app
          api_key: ${{secrets.OCTOPUS_API_KEY}}

      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          space: 'Pattern - Feature Toggles'
          project: 'Hello World (with Feature Toggles)'
          packages: | 
            feature-toggles-hello-world:${{ github.sha }}


     
          
        

      


