name: Trigger auto deployment for feature-toggles-hello-world

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
      
  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
            login-server: helloworldfeaturetoggles.azurecr.io
            username:  ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
            password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}  
      - run: |
          docker build ${{ github.workspace }}/HelloWorld -t helloworldfeaturetoggles.azurecr.io/helloworld:${{ github.sha }}
          docker push helloworldfeaturetoggles.azurecr.io/helloworld:${{ github.sha }}

      - name: Login to Octopus Deploy 🐙
        uses: OctopusDeploy/login@v1
        with: 
          server: https://samples.octopus.app
          api_key: ${{secrets.OCTOPUS_API_KEY}}

      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          space: 'Pattern - Feature Toggles'
          project: 'Hello World (with Feature Toggles)'
          packages: | 
            helloworld:${{ github.sha }}


     
          
        

      


