name: Trigger auto deployment for feature-toggles-hello-world

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'HelloWorld/**'
    - '.github/workflows/feature-toggles-hello-world-AutoDeployTrigger-cbcd06fb-ef9f-4baa-af9d-bb9ecfb5f992.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FEATURETOGGLESHELLOWORLD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FEATURETOGGLESHELLOWORLD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FEATURETOGGLESHELLOWORLD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/HelloWorld 
          registryUrl: featuretoggleshelloworld.azurecr.io
          registryUsername: ${{ secrets.FEATURETOGGLESHELLOWORLD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FEATURETOGGLESHELLOWORLD_REGISTRY_PASSWORD }}
          containerAppName: feature-toggles-hello-world
          resourceGroup: feature-toggles-hello-world
          imageToBuild: featuretoggleshelloworld.azurecr.io/feature-toggles-hello-world:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


